# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "简体中文"
title = "vobl"
weight = 1
[en]
languageName = "English"
languagedirection = "ltr"
title = "vobl"
weight = 2
